# Loading Modules & Data

In [24]:
import nltk
import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt

# Setting environment to ignore future warnings
import warnings
warnings.simplefilter('ignore')


# Importing Models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import MultinomialNB

import time

# Importing Evaluation matrces
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
# from sklearn.metrics import plot_confusion_matrix

from sklearn.model_selection import train_test_split



pd.options.display.max_rows = 50
pd.options.display.max_columns = 50

In [15]:
df = pd.read_csv("/Users/jaynahalai/Desktop/Customer-Vunerability/data/feature_engineered_data.csv")
df.head()

,Product,Sub-product,vunerable_customer,cancelation_period_month,issue_source,Issue,State,Company response to consumer,Timely response?,gender_cat,age,income,children,vulnerability category,negative,positive,sentiment,Channel_of_communication,job,education,20,Self Disclosed Vulnerability,escalated to ombudsman,pca0,pca1,...,pca76,pca77,pca78,pca79,pca80,pca81,pca82,pca83,pca84,pca85,pca86,pca87,pca88,pca89,pca90,pca91,pca92,pca93,pca94,pca95,pca96,pca97,pca98,pca99,vulnerability_level
0,13,15,0,3,8,110,15,1,1,1,27.000000,72578.64234,0,9,0.037,0.189,0,0,3,1,1523,0,0,0.130525,-0.062851,...,-0.016782,0.029389,-0.001882,-0.080970,-0.037437,-0.012497,-0.039954,-0.013242,0.014899,-0.014768,-0.109648,0.007327,-0.002506,0.024325,-0.025375,0.003078,-0.032480,0.039531,0.026129,-0.056312,0.025610,-0.018739,0.041388,0.043857,0
1,8,15,0,2,4,110,31,1,1,0,29.000000,55951.19927,1,12,0.084,0.036,1,1,7,1,1514,0,0,-0.117334,-0.023864,...,0.209029,0.013610,0.160490,-0.105735,-0.014873,-0.074840,0.078940,0.031276,0.028240,-0.019174,-0.084871,-0.027865,-0.014845,0.015323,-0.100427,0.066069,0.010729,0.050876,0.050528,-0.084910,-0.055923,-0.010446,-0.015447,-0.138871,0
2,1,15,0,1,4,110,24,1,1,1,38.000000,36691.68277,1,5,0.079,0.034,1,1,5,1,1551,0,0,0.041562,-0.085188,...,0.191194,0.006002,0.149153,-0.092142,-0.015676,-0.071803,0.076749,0.030256,0.023466,-0.031396,-0.080661,-0.024936,-0.017138,0.020916,-0.104523,0.058251,0.016710,0.047359,0.047836,-0.079153,-0.054333,-0.013270,-0.008450,-0.136965,0
3,9,15,0,3,7,110,35,1,1,0,64.000000,52277.27409,3,5,0.108,0.108,1,4,4,2,1517,0,0,0.011165,0.092194,...,0.009350,-0.015145,0.028659,0.102552,0.006794,0.018821,0.001720,-0.004155,0.052588,-0.027803,-0.013318,0.002077,0.001556,-0.032585,0.037253,0.045771,0.033589,-0.037606,-0.031327,-0.024440,0.013844,0.003599,0.074967,0.024568,0
4,9,40,0,0,8,157,46,1,1,0,36.388486,54189.93763,1,2,0.000,0.091,1,0,5,2,1511,0,0,-0.208048,-0.031526,...,0.012324,-0.000491,-0.001285,-0.084822,-0.018350,0.009601,-0.013549,0.037529,-0.052336,-0.005467,0.043297,0.023196,-0.029241,-0.002351,-0.061355,-0.028840,-0.055117,0.025611,-0.032666,0.005372,0.012969,0.006608,0.060914,-0.040923,0

In [16]:
df['vulnerability_level'].value_counts()

vulnerability_level
0    191870
2    191870
3    191870
4    191870
1    191870
Name: count, dtype: int64

In [17]:
df.shape

(959350, 124)

In [18]:
df.head()

,Product,Sub-product,vunerable_customer,cancelation_period_month,issue_source,Issue,State,Company response to consumer,Timely response?,gender_cat,age,income,children,vulnerability category,negative,positive,sentiment,Channel_of_communication,job,education,20,Self Disclosed Vulnerability,escalated to ombudsman,pca0,pca1,...,pca76,pca77,pca78,pca79,pca80,pca81,pca82,pca83,pca84,pca85,pca86,pca87,pca88,pca89,pca90,pca91,pca92,pca93,pca94,pca95,pca96,pca97,pca98,pca99,vulnerability_level
0,13,15,0,3,8,110,15,1,1,1,27.000000,72578.64234,0,9,0.037,0.189,0,0,3,1,1523,0,0,0.130525,-0.062851,...,-0.016782,0.029389,-0.001882,-0.080970,-0.037437,-0.012497,-0.039954,-0.013242,0.014899,-0.014768,-0.109648,0.007327,-0.002506,0.024325,-0.025375,0.003078,-0.032480,0.039531,0.026129,-0.056312,0.025610,-0.018739,0.041388,0.043857,0
1,8,15,0,2,4,110,31,1,1,0,29.000000,55951.19927,1,12,0.084,0.036,1,1,7,1,1514,0,0,-0.117334,-0.023864,...,0.209029,0.013610,0.160490,-0.105735,-0.014873,-0.074840,0.078940,0.031276,0.028240,-0.019174,-0.084871,-0.027865,-0.014845,0.015323,-0.100427,0.066069,0.010729,0.050876,0.050528,-0.084910,-0.055923,-0.010446,-0.015447,-0.138871,0
2,1,15,0,1,4,110,24,1,1,1,38.000000,36691.68277,1,5,0.079,0.034,1,1,5,1,1551,0,0,0.041562,-0.085188,...,0.191194,0.006002,0.149153,-0.092142,-0.015676,-0.071803,0.076749,0.030256,0.023466,-0.031396,-0.080661,-0.024936,-0.017138,0.020916,-0.104523,0.058251,0.016710,0.047359,0.047836,-0.079153,-0.054333,-0.013270,-0.008450,-0.136965,0
3,9,15,0,3,7,110,35,1,1,0,64.000000,52277.27409,3,5,0.108,0.108,1,4,4,2,1517,0,0,0.011165,0.092194,...,0.009350,-0.015145,0.028659,0.102552,0.006794,0.018821,0.001720,-0.004155,0.052588,-0.027803,-0.013318,0.002077,0.001556,-0.032585,0.037253,0.045771,0.033589,-0.037606,-0.031327,-0.024440,0.013844,0.003599,0.074967,0.024568,0
4,9,40,0,0,8,157,46,1,1,0,36.388486,54189.93763,1,2,0.000,0.091,1,0,5,2,1511,0,0,-0.208048,-0.031526,...,0.012324,-0.000491,-0.001285,-0.084822,-0.018350,0.009601,-0.013549,0.037529,-0.052336,-0.005467,0.043297,0.023196,-0.029241,-0.002351,-0.061355,-0.028840,-0.055117,0.025611,-0.032666,0.005372,0.012969,0.006608,0.060914,-0.040923,0

In [19]:
y = df["vulnerability_level"]
X = df.drop("vulnerability_level", axis=1)

In [20]:
X

,Product,Sub-product,vunerable_customer,cancelation_period_month,issue_source,Issue,State,Company response to consumer,Timely response?,gender_cat,age,income,children,vulnerability category,negative,positive,sentiment,Channel_of_communication,job,education,20,Self Disclosed Vulnerability,escalated to ombudsman,pca0,pca1,...,pca75,pca76,pca77,pca78,pca79,pca80,pca81,pca82,pca83,pca84,pca85,pca86,pca87,pca88,pca89,pca90,pca91,pca92,pca93,pca94,pca95,pca96,pca97,pca98,pca99
0,13,15,0,3,8,110,15,1,1,1,27.000000,72578.642340,0,9,0.037000,0.189000,0,0,3,1,1523,0,0,0.130525,-0.062851,...,0.006477,-0.016782,0.029389,-0.001882,-0.080970,-0.037437,-0.012497,-0.039954,-0.013242,0.014899,-0.014768,-0.109648,0.007327,-0.002506,0.024325,-0.025375,0.003078,-0.032480,0.039531,0.026129,-0.056312,0.025610,-0.018739,0.041388,0.043857
1,8,15,0,2,4,110,31,1,1,0,29.000000,55951.199270,1,12,0.084000,0.036000,1,1,7,1,1514,0,0,-0.117334,-0.023864,...,0.010919,0.209029,0.013610,0.160490,-0.105735,-0.014873,-0.074840,0.078940,0.031276,0.028240,-0.019174,-0.084871,-0.027865,-0.014845,0.015323,-0.100427,0.066069,0.010729,0.050876,0.050528,-0.084910,-0.055923,-0.010446,-0.015447,-0.138871
2,1,15,0,1,4,110,24,1,1,1,38.000000,36691.682770,1,5,0.079000,0.034000,1,1,5,1,1551,0,0,0.041562,-0.085188,...,0.010802,0.191194,0.006002,0.149153,-0.092142,-0.015676,-0.071803,0.076749,0.030256,0.023466,-0.031396,-0.080661,-0.024936,-0.017138,0.020916,-0.104523,0.058251,0.016710,0.047359,0.047836,-0.079153,-0.054333,-0.013270,-0.008450,-0.136965
3,9,15,0,3,7,110,35,1,1,0,64.000000,52277.274090,3,5,0.108000,0.108000,1,4,4,2,1517,0,0,0.011165,0.092194,...,0.094646,0.009350,-0.015145,0.028659,0.102552,0.006794,0.018821,0.001720,-0.004155,0.052588,-0.027803,-0.013318,0.002077,0.001556,-0.032585,0.037253,0.045771,0.033589,-0.037606,-0.031327,-0.024440,0.013844,0.003599,0.074967,0.024568
4,9,40,0,0,8,157,46,1,1,0,36.388486,54189.937630,1,2,0.000000,0.091000,1,0,5,2,1511,0,0,-0.208048,-0.031526,...,0.012470,0.012324,-0.000491,-0.001285,-0.084822,-0.018350,0.009601,-0.013549,0.037529,-0.052336,-0.005467,0.043297,0.023196,-0.029241,-0.002351,-0.061355,-0.028840,-0.055117,0.025611,-0.032666,0.005372,0.012969,0.006608,0.060914,-0.040923
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
959345,0,10,1,2,6,89,51,1,1,0,38.000000,73804.423798,0,7,0.051267,0.033213,1,1,0,0,1505,0,0,-0.023461,-0.005232,...,0.003643,0.030310,0.009896,0.053499,-0.037839,-0.017952,0.008115,0.014143,-0.014965,0.096707,0.046281,0.015248,-0.032091,0.017655,-0.062569,0.079872,0.005624,-0.040288,0.039992,0.003087,-0.031597,-0.054031,-0.017774,0.030685,0.048500
959346,0,16,1,0,7,19,42,2,1,0,50.194070,74710.420874,2,7,0.066220,0.041172,1,2,2,0,1505,0,0,0.130070,0.469124,...,-0.015912,0.059225,0.015142,0.023938,-0.004880,-0.010411,-0.032727,0.042328,0.027307,0.026706,0.020262,-0.054674,-0.006614,0.000243,0.040712,-0.049970,0.073471,0.013152,-0.007426,0.042565,-0.037076,-0.020647,0.039573,-0.009419,-0.024260
959347,4,38,1,3,0,53,19,0,1,0,36.003087,73070.958261,1,7,0.135988,0.042000,1,2,6,0,1542,0,0,-0.070110,-0.059107,...,0.014879,0.024222,0.004305,-0.031144,0.010472,0.069203,-0.004779,0.032672,-0.039374,0.015194,0.019754,-0.163876,0.008734,-0.011262,0.005681,0.068880,-0.014728,0.005495,-0.058606,0.019860,-0.070051,0.024482,-0.006549,-0.004970,-0.033462
959348,13,73,1,0,6,97,40,1,1,1,45.881543,72944.453836,0,3,0.120589,0.000843,1,2,2,0,1523,0,0,-0.203411,-0.008381,...,-0.060340,0.000144,0.032231,-0.019703,0.052237,-0.018342,-0.070552,0.040331,0.021921,0.050245,0.075247,0.033560,-0.056474,0.003014,-0.003908,-0.022091,0.001154,0.019593,-0.089023,0.088422,0.029871,-0.012628,-0.078244,-0.023105,0.063978
959349,4,15,1,2,3,34,34,1,1,0,28.638836,12464.109295,0,10,0.084485,0.110089,1,3,6,1,1539,0,0,0.201877,-0.177288,...,0.048001,0.009198,-0.059210,-0.048158,0.016583,-0.025562,-0.004236,0.006847,0.022220,0.028129,0.027945,0.002378,0.030692,0.019471,-0.016826,0.066817,-0.041759,0.014643,-0.052063,0.010863,0.020671,0.079209,0.054636,0.068416,0.016690

In [21]:
y

0         0
1         0
2         0
3         0
4         0
         ..
959345    4
959346    4
959347    4
959348    4
959349    4
Name: vulnerability_level, Length: 959350, dtype: int64

# Modeling

- Decision Tree Classifier,

- Random Forest,

- Gradient Boost,

- XG Boost

Metrics:
- accuracy 

- F1 score

- AUC

- ROC curve 

- confusion matrics

In [26]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [27]:
X_train

,Product,Sub-product,vunerable_customer,cancelation_period_month,issue_source,Issue,State,Company response to consumer,Timely response?,gender_cat,age,income,children,vulnerability category,negative,positive,sentiment,Channel_of_communication,job,education,20,Self Disclosed Vulnerability,escalated to ombudsman,pca0,pca1,...,pca75,pca76,pca77,pca78,pca79,pca80,pca81,pca82,pca83,pca84,pca85,pca86,pca87,pca88,pca89,pca90,pca91,pca92,pca93,pca94,pca95,pca96,pca97,pca98,pca99
615457,9,22,1,1,2,98,52,2,1,0,29.404686,76098.193317,0,2,0.143182,0.047144,1,1,1,1,1505,0,0,0.193194,-0.030167,...,0.003817,-0.010648,0.024297,0.037851,0.007379,0.007109,-0.008962,0.007548,0.056797,-0.005124,0.020916,0.022433,0.004841,-0.015733,0.007410,-0.013237,-0.005790,-0.012217,-0.003145,-0.005156,0.003936,0.002996,-0.001957,0.029274,-0.009236
421501,6,71,1,0,7,133,34,1,1,0,36.514608,73151.921315,0,11,0.085510,0.048578,0,0,1,1,1515,0,0,-0.047188,0.011476,...,0.013770,-0.027458,0.009443,0.038652,-0.014566,0.008224,-0.018876,0.037452,-0.007645,-0.033865,-0.017762,0.050864,-0.023435,-0.009308,-0.029199,-0.014984,0.012058,0.010544,-0.034050,-0.006413,0.009448,0.028000,0.018368,0.006874,-0.036353
902870,7,29,1,0,3,124,18,1,1,0,22.963667,14081.493071,1,1,0.145292,0.106128,1,1,6,0,1523,0,0,-0.031039,-0.088461,...,0.017206,-0.012351,0.005213,-0.044004,-0.013418,0.023795,0.019976,-0.012955,0.022449,-0.002616,0.015269,-0.007903,-0.023599,0.011384,0.011825,0.025162,-0.002616,0.015369,-0.030216,-0.007528,-0.008851,-0.011189,-0.017601,0.036476,-0.010995
543370,7,63,1,3,7,51,13,1,1,0,37.892021,82805.241624,1,2,0.158960,0.085352,1,0,5,1,1514,0,0,-0.111143,-0.048669,...,0.012851,-0.006776,0.004924,-0.008185,-0.016916,0.009596,-0.000295,0.016865,0.035907,0.024984,-0.011621,0.004532,0.032791,0.002413,0.012803,-0.016016,-0.004731,-0.014516,-0.022849,-0.005266,0.012590,0.021396,0.005561,-0.006888,0.001346
291082,9,35,1,0,4,30,12,1,1,1,37.421104,81063.396536,0,12,0.112797,0.083948,1,0,4,2,1520,0,0,-0.048630,-0.144729,...,-0.027817,-0.019862,-0.027927,0.008327,0.034546,-0.001609,0.035812,0.022660,0.033004,0.035153,-0.001573,-0.030624,0.018990,-0.001771,0.006321,-0.000486,0.029583,0.033647,0.028475,-0.014814,-0.010983,0.007468,0.005260,0.012681,0.019753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
466071,10,23,1,0,6,49,58,1,1,0,28.959107,75693.081787,2,12,0.004703,0.099747,1,2,2,1,1503,0,0,-0.103666,0.092674,...,-0.076500,0.019151,-0.025960,-0.072092,-0.036972,0.089863,0.089923,0.013139,-0.000822,0.060077,0.003443,-0.048387,-0.077212,0.049072,-0.061123,-0.014292,-0.017299,-0.037261,-0.041458,0.024135,-0.009420,-0.044231,-0.007800,0.005619,0.072649
834034,12,52,1,0,5,36,31,1,1,1,43.563673,84825.051141,0,3,0.057179,0.045594,1,0,1,0,1517,0,0,-0.191358,0.010811,...,-0.002596,0.011235,-0.007312,-0.050855,-0.022072,0.001213,0.005361,0.034069,0.008263,0.015279,-0.027885,0.008521,0.000486,-0.002557,0.026065,-0.000917,0.008572,-0.024029,-0.032637,0.000034,-0.003953,-0.001921,-0.012600,0.023004,0.007352
316517,1,71,1,1,0,82,50,1,1,0,34.797299,75325.264023,1,3,0.055872,0.076939,1,3,5,2,1550,1,0,-0.185502,0.000793,...,-0.044979,-0.047650,-0.040598,-0.012408,-0.007021,0.008040,0.031305,0.023603,-0.041594,0.049918,0.067486,0.064577,0.000276,-0.001277,-0.010153,-0.020740,-0.018602,-0.033286,0.055763,0.021657,0.007388,0.001683,-0.048281,0.007878,-0.047314
957595,6,11,1,2,3,91,35,1,1,0,25.000000,14057.748040,1,0,0.082586,0.091781,1,0,2,0,1517,0,0,-0.007548,-0.056955,...,0.020509,-0.006826,-0.045054,-0.024771,-0.069935,0.176910,0.011888,0.018010,0.075709,0.002739,-0.054417,0.012729,-0.007304,-0.051660,-0.064530,0.016842,0.012357,-0.017974,0.012091,0.005651,0.011373,-0.019782,0.014401,0.010794,0.006075
426046,7,34,1,1,2,38,27,1,1,0,33.832736,76307.809566,0,4,0.120691,0.047826,1,0,4,1,1585,0,0,0.210518,-0.109138,...,0.007177,-0.048788,0.016364,-0.026669,-0.016925,-0.030018,-0.013514,0.016208,-0.000756,-0.016731,-0.045024,0.018582,0.023340,0.051851,-0.031780,-0.005413,-0.008363,0.001091,-0.002471,0.026211,0.030742,0.027953,-0.023563,-0.002665,0.008056

In [28]:
X_test

,Product,Sub-product,vunerable_customer,cancelation_period_month,issue_source,Issue,State,Company response to consumer,Timely response?,gender_cat,age,income,children,vulnerability category,negative,positive,sentiment,Channel_of_communication,job,education,20,Self Disclosed Vulnerability,escalated to ombudsman,pca0,pca1,...,pca75,pca76,pca77,pca78,pca79,pca80,pca81,pca82,pca83,pca84,pca85,pca86,pca87,pca88,pca89,pca90,pca91,pca92,pca93,pca94,pca95,pca96,pca97,pca98,pca99
725610,6,37,1,0,1,34,9,1,1,0,55.472991,55537.906122,0,6,0.145739,0.024728,1,1,2,1,1509,0,0,-0.145407,-0.061051,...,0.011570,0.003449,-0.004173,0.015293,-0.013732,-0.030958,-0.006468,0.020166,0.000656,0.051670,-0.014519,0.014325,-0.013146,-0.033828,-0.003145,0.002080,0.002371,0.032759,0.006936,0.000503,-0.071536,-0.027449,-0.004487,-0.002798,-0.014826
766549,11,15,1,2,7,108,8,1,1,0,35.941488,72934.589605,0,0,0.091896,0.123055,1,1,1,1,1519,0,0,-0.039143,-0.078130,...,-0.023987,-0.031106,0.026174,0.070465,0.015947,-0.008662,-0.023336,-0.066781,0.024702,0.013605,-0.021163,0.006971,-0.018900,0.007103,-0.012755,0.010905,0.007291,0.016437,-0.033768,0.024916,0.012493,0.003595,0.006007,-0.005928,0.032613
215775,12,28,1,3,3,28,43,1,0,0,35.169998,78967.365516,1,5,0.060878,0.028258,1,0,5,2,1549,0,0,0.001912,-0.089685,...,-0.002713,-0.012078,-0.000335,0.005013,-0.013653,0.010941,0.011929,-0.004525,-0.038480,-0.054544,0.014845,-0.035492,-0.007716,-0.032972,-0.032364,-0.020667,0.005658,0.015766,-0.028337,0.007890,0.022464,0.000957,-0.011291,0.011857,0.031148
946609,5,10,1,3,4,135,32,1,1,0,35.187555,74725.047096,0,4,0.082958,0.062791,1,1,0,0,1506,0,0,0.142853,-0.107479,...,-0.000580,-0.055981,-0.007308,-0.015430,0.038543,-0.006246,0.001925,-0.010382,-0.040365,-0.020214,0.047030,-0.047777,0.007766,0.023178,-0.025652,0.011079,-0.012409,0.022558,0.083247,0.022839,-0.000053,-0.010942,0.075209,0.026717,0.029450
584696,3,33,1,2,4,147,52,1,1,0,24.509821,14063.253061,0,2,0.155981,0.080804,0,0,5,1,1543,0,0,-0.002100,0.156761,...,0.014369,0.002628,0.030531,-0.003301,0.032135,0.029932,0.015171,0.026861,-0.020812,-0.007337,-0.003927,-0.012448,-0.009088,0.014982,0.001941,0.039669,-0.003036,0.007383,0.024281,0.014742,0.019011,-0.012608,-0.004678,-0.001051,0.006422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31224,4,7,0,2,6,84,20,1,1,0,24.000000,15739.611360,1,7,0.112000,0.000000,1,1,3,1,1543,0,0,0.098892,0.110326,...,0.005204,0.004746,-0.024619,-0.018993,-0.070887,0.122698,-0.059038,0.030140,0.030386,0.004059,-0.038711,0.025563,-0.034019,-0.035946,-0.038254,-0.032272,0.039438,0.029576,0.008531,0.045383,-0.009770,-0.016196,-0.010798,-0.008181,0.036005
479949,10,37,1,1,7,14,10,1,1,1,37.000000,72917.136462,0,10,0.118301,0.067662,1,0,5,1,1521,0,0,-0.014715,0.087243,...,0.063619,0.015256,-0.037790,0.047153,-0.008019,-0.003590,0.010629,-0.058054,0.025875,-0.004186,0.056696,-0.044276,-0.063614,0.016434,-0.034828,0.044192,-0.047242,-0.032612,-0.052471,-0.025741,0.027397,-0.016838,0.018298,0.018351,0.025664
121698,6,22,0,0,2,49,43,1,1,0,25.000000,13054.446050,0,1,0.224000,0.055000,1,3,5,1,1587,0,0,0.206147,0.126097,...,-0.042085,-0.003565,-0.037161,0.020058,0.047500,0.014679,0.024413,-0.006881,0.010391,-0.009951,0.003156,-0.029952,0.021408,-0.024345,0.025163,0.009609,0.033589,0.025606,0.026878,-0.000230,0.013660,0.017953,0.018435,0.005115,-0.033401
287443,5,26,1,0,4,47,37,1,1,0,40.266113,76290.131145,0,6,0.081481,0.096471,1,1,3,2,1512,0,0,0.005781,-0.041047,...,0.066548,-0.018708,-0.050897,0.010098,-0.052336,-0.010636,0.017667,0.003734,0.005634,0.019089,0.005014,-0.003885,0.015821,0.045269,0.005074,0.025243,-0.029289,0.000871,0.007631,-0.001271,-0.004496,0.018204,0.026863,-0.017248,-0.036215
243404,10,29,1,1,4,55,16,1,1,0,35.703812,80995.097498,0,8,0.146930,0.043422,1,0,5,2,1521,0,0,-0.062811,0.023645,...,-0.020755,-0.033722,-0.030613,-0.004142,0.021913,0.005760,0.034001,0.028685,0.022153,0.006692,-0.017822,-0.024275,0.039754,0.000573,0.006099,0.000109,0.021397,0.040902,0.011872,-0.025956,-0.002830,0.010284,-0.001151,0.035617,0.000635

In [29]:
y_train

615457    3
421501    2
902870    4
543370    2
291082    1
         ..
466071    2
834034    4
316517    1
957595    4
426046    2
Name: vulnerability_level, Length: 767480, dtype: int64

In [30]:
y_test

725610    3
766549    3
215775    1
946609    4
584696    3
         ..
31224     0
479949    2
121698    0
287443    1
243404    1
Name: vulnerability_level, Length: 191870, dtype: int64

## DecisionTreeClassifier

In [32]:
d_tree = DecisionTreeClassifier()

d_tree.fit(X_train,y_train)

DecisionTreeClassifier()

In [34]:
d_tree.score(X_train,y_train)

1.0

In [35]:
d_tree.score(X_test,y_test)

0.9846302183770261

## DecisionTreeClassifier with hyper parameter tuning