# Loading Modules & Data

In [1]:
import nltk
import numpy as np
import pandas as pd
import seaborn as sns
import plotly.express as px
import matplotlib.pyplot as plt

# Setting environment to ignore future warnings
import warnings
warnings.simplefilter('ignore')


pd.options.display.max_rows = 50
pd.options.display.max_columns = 50

In [2]:
df = pd.read_csv("CDdataset_v15_1_19012023.csv").iloc[:, 4:]
df.head()

,Feedback ID,Date received,Product,Sub-product,vunerable_customer,cancelation_period_month,issue_source,Issue,Sub-issue,Consumer complaint narrative,Company public response,State,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,gender_cat,age,rejected,Recommended Pathway Switch,income,children,vulnerability category,vulnerability type,negative,positive,neutral,sentiment,Channel_of_communication,job,education,cust_ID,product_ID,vulnerability_score,vulnerability_level,vulnerability source,Self Disclosed Vulnerability,escalated to ombudsman,High level issue,Product_type,Claims_Aging
0,3186792,03/21/2019,Theft,Credit reporting,non-vunerable,Dec-24,Repayment,Problem with a credit reporting company's inve...,Their investigation did not fix an error on yo...,There is an account reporting on my credit rep...,Company has responded to the consumer and the ...,GA,03/21/2019,Closed with explanation,Yes,NaN,Male,27.0,0,No Change,72578.64234,0,Poor or non-existent digital skills,NaN,0.037,0.189,0.774,negative,Chatbot,management,secondary,1749229,1523,0,Level 0 - not vulnerable,NaN,0,0,billing disputes,Home insurance,NaN
1,3184692,03/19/2019,Occupational Health,Credit reporting,non-vunerable,24+,Misselling,Problem with a credit reporting company's inve...,Their investigation did not fix an error on yo...,XXXX and Transunion are reporting incorrectly ...,Company has responded to the consumer and the ...,MO,03/19/2019,Closed with explanation,Yes,NaN,Female,29.0,0,No Change,55951.19927,1,learning difficulties,NaN,0.084,0.036,0.880,neutral,Mobile App,unemployed,secondary,1749230,1514,0,Level 0 - not vulnerable,NaN,0,0,product modification,Health insurance,NaN
2,3184195,03/19/2019,Accidental Damage,Credit reporting,non-vunerable,03-Dec,Misselling,Problem with a credit reporting company's inve...,Their investigation did not fix an error on yo...,XXXX and Transunion are reporting incorrectly...,Company has responded to the consumer and the ...,LA,03/19/2019,Closed with explanation,Yes,NaN,Male,38.0,0,No Change,36691.68277,1,Low English language skills,NaN,0.079,0.034,0.886,neutral,Mobile App,services,secondary,1749231,1551,0,Level 0 - not vulnerable,NaN,0,0,other,Motor insurance,3.0
3,3183589,03/18/2019,Online GP,Credit reporting,non-vunerable,Dec-24,Product Functionality,Problem with a credit reporting company's inve...,Investigation took more than 30 days,"On XX/XX/XXXX, I sent a request to the three c...",Company has responded to the consumer and the ...,NC,03/18/2019,Closed with explanation,Yes,NaN,Female,64.0,0,No Change,52277.27409,3,Low English language skills,NaN,0.108,0.108,0.784,neutral,Phone Call,retired,tertiary,1749232,1517,0,Level 0 - not vulnerable,NaN,0,0,inability to manage product,Health insurance,3.0
4,3182609,03/18/2019,Online GP,Medical debt,non-vunerable,0-3,Repayment,Written notification about debt,Didn't receive notice of right to dispute,i never received anything stating that i owed ...,Company believes it acted appropriately as aut...,PA,03/18/2019,Closed with explanation,Yes,NaN,Female,NaN,0,No Change,54189.93763,1,Bereavement,NaN,0.000,0.091,0.909,neutral,Chatbot,services,tertiary,1749233,1511,0,Level 0 - not vulnerable,NaN,0,0,struggling to repay,Health insurance,NaN

In [2]:
df = pd.read_csv("/Users/jethrodatamwinapeawini/Desktop/Customer-Vunerability/data/feature_engineered_data.csv")

In [3]:
df.head()

,Product,Sub-product,vunerable_customer,cancelation_period_month,issue_source,Issue,State,Company response to consumer,Timely response?,gender_cat,age,income,children,vulnerability category,negative,positive,sentiment,Channel_of_communication,job,education,20,Self Disclosed Vulnerability,escalated to ombudsman,pca0,pca1,...,pca76,pca77,pca78,pca79,pca80,pca81,pca82,pca83,pca84,pca85,pca86,pca87,pca88,pca89,pca90,pca91,pca92,pca93,pca94,pca95,pca96,pca97,pca98,pca99,vulnerability_level
0,13,15,0,3,8,110,15,1,1,1,27.000000,72578.64234,0,9,0.037,0.189,0,0,3,1,1523,0,0,0.130525,-0.062851,...,-0.016782,0.029389,-0.001882,-0.080970,-0.037437,-0.012497,-0.039954,-0.013242,0.014899,-0.014768,-0.109648,0.007327,-0.002506,0.024325,-0.025375,0.003078,-0.032480,0.039531,0.026129,-0.056312,0.025610,-0.018739,0.041388,0.043857,0
1,8,15,0,2,4,110,31,1,1,0,29.000000,55951.19927,1,12,0.084,0.036,1,1,7,1,1514,0,0,-0.117334,-0.023864,...,0.209029,0.013610,0.160490,-0.105735,-0.014873,-0.074840,0.078940,0.031276,0.028240,-0.019174,-0.084871,-0.027865,-0.014845,0.015323,-0.100427,0.066069,0.010729,0.050876,0.050528,-0.084910,-0.055923,-0.010446,-0.015447,-0.138871,0
2,1,15,0,1,4,110,24,1,1,1,38.000000,36691.68277,1,5,0.079,0.034,1,1,5,1,1551,0,0,0.041562,-0.085188,...,0.191194,0.006002,0.149153,-0.092142,-0.015676,-0.071803,0.076749,0.030256,0.023466,-0.031396,-0.080661,-0.024936,-0.017138,0.020916,-0.104523,0.058251,0.016710,0.047359,0.047836,-0.079153,-0.054333,-0.013270,-0.008450,-0.136965,0
3,9,15,0,3,7,110,35,1,1,0,64.000000,52277.27409,3,5,0.108,0.108,1,4,4,2,1517,0,0,0.011165,0.092194,...,0.009350,-0.015145,0.028659,0.102552,0.006794,0.018821,0.001720,-0.004155,0.052588,-0.027803,-0.013318,0.002077,0.001556,-0.032585,0.037253,0.045771,0.033589,-0.037606,-0.031327,-0.024440,0.013844,0.003599,0.074967,0.024568,0
4,9,40,0,0,8,157,46,1,1,0,36.388486,54189.93763,1,2,0.000,0.091,1,0,5,2,1511,0,0,-0.208048,-0.031526,...,0.012324,-0.000491,-0.001285,-0.084822,-0.018350,0.009601,-0.013549,0.037529,-0.052336,-0.005467,0.043297,0.023196,-0.029241,-0.002351,-0.061355,-0.028840,-0.055117,0.025611,-0.032666,0.005372,0.012969,0.006608,0.060914,-0.040923,0

In [4]:
X = df["vulnerability_level"]
y = df.drop("vulnerability_level", axis=1, inplace=True)

# Modeling

In [10]:
# from sklearn.model_selection import train_test_split
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [9]:
# # Importing Models
# from sklearn.linear_model import LogisticRegression
# from sklearn.svm import SVC
# from sklearn.neighbors import KNeighborsClassifier
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.ensemble import AdaBoostClassifier
# from sklearn.tree import DecisionTreeClassifier
# from sklearn.naive_bayes import MultinomialNB

# # Importing Evaluation matrces
# from sklearn.metrics import accuracy_score
# from sklearn.metrics import precision_score
# from sklearn.metrics import recall_score
# from sklearn.metrics import f1_score
# from sklearn.metrics import confusion_matrix
# from sklearn.metrics import classification_report
# from sklearn.metrics import plot_confusion_matrix


# # check the performance on diffrent regressor
# models = []
# models.append(('LogisitcRegression', LogisticRegression()))
# models.append(('DecisionTreeClassifier', DecisionTreeClassifier()))
# models.append(('RandomForestClassifier', RandomForestClassifier()))


# # metrices to store performance
# acc = []
# pre = []
# f1 = []
# con = []
# rec = []


# import time
# i = 0
# for name,model in models:
#     i = i+1
#     start_time = time.time()
    
#     # Fitting model to the Training set
#     clf = model
#     clf.fit(X_train, y_train)
    
#     # predict values
#     y_pred = clf.predict(X_test)
    
#     # Accuracy
#     accuracy = accuracy_score(y_test, y_pred)
#     acc.append(accuracy)
#     # Precision
#     precision = precision_score(y_test, y_pred, average=None)
#     pre.append(precision)
#     # Recall
#     recall = recall_score(y_test, y_pred, average=None)
#     rec.append(recall)
#     # F1 Score
#     f1_sco = f1_score(y_test, y_pred, average=None)
#     f1.append(f1_sco)
#     # Confusion Matrix
#     confusion_mat = confusion_matrix(y_test, y_pred)
#     con.append(confusion_mat)
#     # Report
#     report = classification_report(y_test, y_pred)


#     print("+","="*100,"+")
#     print('\033[1m' + f"\t\t\t{i}-For {name} The Performance result is: " + '\033[0m')
#     print("+","="*100,"+")
#     print('Accuracy : ', accuracy)   
#     print("-"*50)
#     print('F1 : ', f1_sco)
#     print("-"*50)
#     print('Reacll : ', recall)
#     print("-"*50)
#     print('Precision : ', precision)
#     print("-"*50)
#     print('Confusion Matrix....\n', confusion_mat)
#     print("-"*50)
#     print('Classification Report....\n', report)
#     print("-"*50)
#     print('Plotting Confusion Matrix...\n')
    
#     class_labels = list(y_test.value_counts().sort_index().index)
#     plt.figure(figsize=(12, 10))
#     ax = sns.heatmap(confusion_mat, annot=True, cmap='YlGnBu', fmt='d')
#     ax.set_xticklabels(class_labels, rotation=65)
#     ax.set_yticklabels(class_labels, rotation=0)
#     plt.show()


    
#     print("\t\t\t\t\t\t\t-----------------------------------------------------------")
#     print(f"\t\t\t\t\t\t\t Time for detection ({name}) : {round((time.time() - start_time), 3)} seconds...")
#     print("\t\t\t\t\t\t\t-----------------------------------------------------------")
#     print()

In [75]:
comp = pd.DataFrame({"Model": dict(models).keys(), "Accuracy": acc, "Precision": pre, "Recall": rec, "F1_Score": f1, "Confusion Matrix": con})
comp

,Model,Accuracy,Precision,Recall,F1_Score,Confusion Matrix
0,LogisitcRegression,0.333632,"[0.44113215669393024, 0.3171800852569774, 0.29...","[0.534071661237785, 0.6137902409919842, 0.3223...","[0.48317321860081336, 0.41823468585114937, 0.3...","[[20495, 4632, 3112, 1513, 8623], [1953, 23661..."
1,DecisionTreeClassifier,0.985188,"[1.0, 0.9982128056361376, 0.9728195469052477, ...","[1.0, 0.9997405898985706, 0.9737875772493977, ...","[1.0, 0.9989761136384254, 0.9733033213808988, ...","[[38375, 0, 0, 0, 0], [0, 38539, 10, 0, 0], [0..."
2,RandomForestClassifier,0.999656,"[1.0, 1.0, 0.9985616402531513, 0.9997912099384...","[1.0, 1.0, 0.9998690688174295, 0.9985402981962...","[1.0, 1.0, 0.9992149268573521, 0.9991653625456...","[[38375, 0, 0, 0, 0], [0, 38549, 0, 0, 0], [0,..."